pjt04/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
'''
index

detail
    delete
    edit : update

new :create

'''
urlpatterns = [
    path('', views.index, name='index'),
    
    #detail
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),

    #new
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    #search
    path('search/', views.search, name='search')
]

pjt04/pjt04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

pjt04/movies/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)

    def __str__(self):
        return self.title

pjt04/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
'''
R
index

R
detail

    D
    delete

    U
    edit : update

C
new :create

'''

def index(request):
    movies = Movie.objects.all()

    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request, 'movies/detail.html', context)

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()

    return redirect('movies:index')

def edit(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request, 'movies/edit.html', context)

def new(request):
    return render(request, 'movies/new.html')

def create(request):
    title = request.POST.get('title')
    overview = request.POST.get('overview')
    poster_path = request.POST.get('poster_path')

    movie = Movie(title=title, overview=overview, poster_path=poster_path)
    movie.save()

    return redirect('movies:detail', movie.pk)

def update(request, pk):
    
    movie = Movie.objects.get(pk=pk)

    movie.title = request.POST.get('title')
    movie.overview = request.POST.get('overview')
    movie.poster_path = request.POST.get('poster_path')

    movie.save()

    return redirect('movies:detail', movie.pk)

def search(request):
    search = request.GET.get('search')
    
    movies = Movie.objects.filter(title__contains=search)

    context = {
        'search' : search,
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)
    
    

pjt04/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">title : {{ movie.title }}</h5>
      <hr>
      <p class="card-text">overview : {{ movie.overview }}</p>
      <hr>
      <p class="card-text">poster path : {{ movie.poster_path }}</p>
      <a href="{% url 'movies:edit' movie.pk %}" class='btn btn-primary'>edit</a>
      <a href="{% url 'movies:delete' movie.pk %}" class='btn btn-primary'>delete</a>
    </div>
  </div>
{% endblock body %}

pjt04/movies/templates/movies/edit.html
{% extends 'base.html' %}
{% block body %}
  <form action="{% url 'movies:update' movie.pk %}" method='POST'>
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Title</label>
      <input type="text" class="form-control" id="exampleFormControlInput1" name='title' value={{ movie.title }}>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">overview</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name='overview'>{{ movie.overview }}</textarea>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">posterpath</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name='poster_path'>{{ movie.poster_path }}</textarea>
    </div>
    <input type="submit" name="" id="">
  </form>
{% endblock body %}

pjt04/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
  {% if search|length != 0 %}
    {% if movies|length != 0 %}
      <h5>{{ search }}에 대한 검색 결과는 다음과 같습니다.</h5>
    {% else %}
    <h5>{{ search }}에 대한 검색 결과는 존재하지 않습니다.</h5>
    {% endif %}
  {% endif %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in movies %}
        <tr>
          <th scope="row">{{ movie.pk }}</th>
          <td><a href="{% url 'movies:detail' movie.pk %}" class='text-decoration-none'>{{ movie.title }}</a></td>
        </tr>
      {% endfor %}
  </table>
{% endblock body %}

pjt04/movies/templates/movies/new.html
{% extends 'base.html' %}

{% block body %}
  <form action="{% url 'movies:create' %}" method='POST'>
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Title</label>
      <input type="text" class="form-control" id="exampleFormControlInput1" name='title'>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">overview</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name='overview'></textarea>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">posterpath</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name='poster_path'></textarea>
    </div>
    <input type="submit" name="" id="">
  </form>
{% endblock body %}

pjt04/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'movies:index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'movies:new' %}">New</a>
        </div>
        <form class="d-flex" action="{% url 'movies:search' %}" method='GET'>
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name='search'>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block body %}
    {% endblock body %}
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>