pjt06/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('<str:username>/', views.profile ,name='profile'),
]

pjt06/community/urls.py
from django.urls import path
from . import views
app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

pjt06/pjt06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

pjt06/accounts/models.py
from django.db import models

# Create your models here.

pjt06/community/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    movie_title = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    content = models.TextField()
    rank = models.IntegerField()
    

pjt06/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta():
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

pjt06/community/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta():
        model = Review
        fields = '__all__'

pjt06/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UserChangeForm,
    PasswordChangeForm
)
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.views.decorators.http import *
from django.contrib.auth.models import User
from .forms import CustomUserChangeForm
from django.contrib.auth.decorators import *

@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else:
        form = UserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    if request.method == 'POST':
        #1
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            #2
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

@require_POST
def delete(request):
    request.user.delete()
    return redirect('accounts:login')

@login_required
@require_http_methods(['GET','POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user.username)
    else:
        form = CustomUserChangeForm(instance = request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
@require_http_methods(['GET','POST'])
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/password.html', context)

@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    context = {
        'user' : user,
    }
    return render(request, 'accounts/profile.html', context)

pjt06/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import *
from django.contrib.auth.decorators import *
from .models import Review
from .forms import ReviewForm

# Create your views here.
@require_safe
def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews' : reviews,
    }
    return render(request, 'community/index.html', context)

@login_required
@require_http_methods(['GET','POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else:
        form = ReviewForm()
    context = {
        'form' : form,
    }
    return render(request, 'community/form.html', context)

@require_safe
def detail(request, pk):
    review = get_object_or_404(Review, pk=pk)
    context = {
        'review' : review,
    }
    return render(request, 'community/detail.html', context)

@login_required
@require_http_methods(['GET','POST'])
def update(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('community:detail', pk)

    else:
        form = ReviewForm(instance=review)
    context = {
        'form' : form,
    }
    return render(request, 'community/form.html', context)

@require_POST
@login_required
def delete(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == 'POST':
        review.delete()
        return redirect('community:index')
    else:
        return redirect('community:detail', review.pk)

pjt06/community/templates/community/detail.html
{% extends 'base.html' %}

{% block bd %}
  <p>{{ review.title }}</p>
  <p>{{ review.movie_title }}</p>
  <p>{{ review.content }}</p>
  <p>{{ review.rank }}</p>
  <a href="{% url 'community:update' review.pk %}">update</a>
  <form action="{% url 'community:delete' review.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" name="" id="" value='delete'>
  </form>
{% endblock bd %}

pjt06/community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block bd %}
  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" id="">
  </form>
{% endblock bd %}

pjt06/community/templates/community/index.html
{% extends 'base.html' %}

{% block bd %}
  {% for review in reviews %}
    <a href="{% url 'community:detail' review.pk %}">{{ review.title }}</a>
  {% endfor %}
{% endblock bd %}

pjt06/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% bootstrap_css %}

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'community:index' %}">Index</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'community:create' %}">Create</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile' request.user.username %}">Mypage</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method='POST' id='logout-form'>
                {% csrf_token %}
                <a class="nav-link" onclick="document.querySelector('#logout-form').submit()" href="#">Logout</a>
              </form>
            </li>
          </ul>
        </div>
      {% else %}
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
          </ul>
        </div>
      {% endif %}
    </div>
  </nav>
  {% comment %} <div>
    <a href="{% url 'community:index' %}">index</a>
    {% if request.user.is_authenticated %}
      <a href="{% url 'community:create' %}">create</a>
      <a href="{% url 'accounts:profile' request.user.username %}">mypage</a>
      <form action="{% url 'accounts:logout' %}" method='POST'>
        {% csrf_token %}
        <input type="submit" name="" id="" value='로그아웃'>
      </form>
    {% else %}
      <a href="{% url 'accounts:signup' %}">signup</a>
      <a href="{% url 'accounts:login' %}">login</a>
    {% endif %}
  
  </div> {% endcomment %}
  <div class="container">
    {% block bd %}
    
    {% endblock bd %}   
  </div>
  {% bootstrap_javascript %}
</body>
</html>